package com.menux.menu_x_backend.dto.subscription;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Report generated by subscription audit and repair operations
 */
public class SubscriptionAuditReport {
    
    private LocalDateTime auditTime;
    private List<Long> orphanedSubscriptions;
    private List<MismatchRepair> mismatchesFixed;
    private List<Long> expiredSubscriptionsFixed;
    private int totalSubscriptionsChecked;
    
    public SubscriptionAuditReport() {
        this.auditTime = LocalDateTime.now();
        this.orphanedSubscriptions = new ArrayList<>();
        this.mismatchesFixed = new ArrayList<>();
        this.expiredSubscriptionsFixed = new ArrayList<>();
        this.totalSubscriptionsChecked = 0;
    }
    
    public void addOrphanedSubscription(Long subscriptionId) {
        this.orphanedSubscriptions.add(subscriptionId);
    }
    
    public void addMismatchFixed(Long restaurantId, boolean wasPro, boolean shouldBePro) {
        this.mismatchesFixed.add(new MismatchRepair(restaurantId, wasPro, shouldBePro));
    }
    
    public void addExpiredSubscriptionFixed(Long restaurantId) {
        this.expiredSubscriptionsFixed.add(restaurantId);
    }
    
    public void incrementTotalChecked() {
        this.totalSubscriptionsChecked++;
    }
    
    public boolean hasIssues() {
        return !orphanedSubscriptions.isEmpty() || 
               !mismatchesFixed.isEmpty() || 
               !expiredSubscriptionsFixed.isEmpty();
    }
    
    public int getTotalIssuesFixed() {
        return orphanedSubscriptions.size() + 
               mismatchesFixed.size() + 
               expiredSubscriptionsFixed.size();
    }
    
    // Getters and setters
    public LocalDateTime getAuditTime() {
        return auditTime;
    }
    
    public void setAuditTime(LocalDateTime auditTime) {
        this.auditTime = auditTime;
    }
    
    public List<Long> getOrphanedSubscriptions() {
        return orphanedSubscriptions;
    }
    
    public void setOrphanedSubscriptions(List<Long> orphanedSubscriptions) {
        this.orphanedSubscriptions = orphanedSubscriptions;
    }
    
    public List<MismatchRepair> getMismatchesFixed() {
        return mismatchesFixed;
    }
    
    public void setMismatchesFixed(List<MismatchRepair> mismatchesFixed) {
        this.mismatchesFixed = mismatchesFixed;
    }
    
    public List<Long> getExpiredSubscriptionsFixed() {
        return expiredSubscriptionsFixed;
    }
    
    public void setExpiredSubscriptionsFixed(List<Long> expiredSubscriptionsFixed) {
        this.expiredSubscriptionsFixed = expiredSubscriptionsFixed;
    }
    
    public int getTotalSubscriptionsChecked() {
        return totalSubscriptionsChecked;
    }
    
    public void setTotalSubscriptionsChecked(int totalSubscriptionsChecked) {
        this.totalSubscriptionsChecked = totalSubscriptionsChecked;
    }
    
    /**
     * Inner class to represent a mismatch repair
     */
    public static class MismatchRepair {
        private Long restaurantId;
        private boolean wasPro;
        private boolean shouldBePro;
        private LocalDateTime fixedAt;
        
        public MismatchRepair(Long restaurantId, boolean wasPro, boolean shouldBePro) {
            this.restaurantId = restaurantId;
            this.wasPro = wasPro;
            this.shouldBePro = shouldBePro;
            this.fixedAt = LocalDateTime.now();
        }
        
        // Getters and setters
        public Long getRestaurantId() {
            return restaurantId;
        }
        
        public void setRestaurantId(Long restaurantId) {
            this.restaurantId = restaurantId;
        }
        
        public boolean isWasPro() {
            return wasPro;
        }
        
        public void setWasPro(boolean wasPro) {
            this.wasPro = wasPro;
        }
        
        public boolean isShouldBePro() {
            return shouldBePro;
        }
        
        public void setShouldBePro(boolean shouldBePro) {
            this.shouldBePro = shouldBePro;
        }
        
        public LocalDateTime getFixedAt() {
            return fixedAt;
        }
        
        public void setFixedAt(LocalDateTime fixedAt) {
            this.fixedAt = fixedAt;
        }
    }
}
