spring:
  application:
    name: menu-x-backend
  profiles:
    active: supabase

---
# Supabase Profile (PostgreSQL)
spring:
  config:
    activate:
      on-profile: supabase
  datasource:
    url: ${SUPABASE_DATABASE_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple}
    username: ${SUPABASE_DATABASE_USERNAME:postgres.fxxbzrxcakzbbdvxocsu}
    password: ${SUPABASE_DATABASE_PASSWORD:007$he@M}
    driver-class-name: org.postgresql.Driver
    # HikariCP connection pool configuration for Supabase
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      auto-commit: true
      # PostgreSQL specific settings - disable prepared statement caching to avoid conflicts
      data-source-properties:
        cachePrepStmts: false
        prepStmtCacheSize: 0
        prepStmtCacheSqlLimit: 0
        useServerPrepStmts: false
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: false
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        # Force simple query mode to prevent 'prepared statement already exists' error with PgBouncer
        preferQueryMode: simple
        # Additional PostgreSQL settings for Supabase
        tcpKeepAlive: true
        socketTimeout: 30
        loginTimeout: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Use simple query mode to avoid server-side prepares on Supabase/pgbouncer
        jdbc.prepStmtCacheSize: 0
        jdbc.prepStmtCacheSqlLimit: 0
        jdbc.use_get_generated_keys: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: false
        connection.autocommit: true
        connection.isolation: 2
        jdbc.time_zone: UTC
        temp.use_jdbc_metadata_defaults: false
  # JSON serialization/deserialization timezone for API responses
  # Override via APP_TIME_ZONE env var (e.g., Asia/Dhaka)
  jackson:
    time-zone: ${APP_TIME_ZONE:Asia/Dhaka}
  logging:
    timezone: ${APP_TIME_ZONE:Asia/Dhaka}
  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  time-zone: ${APP_TIME_ZONE:Asia/Dhaka}
  frontend:
    # Frontend base URL used when generating QR code links
    # Override with APP_FRONTEND_URL env var in deployment
    url: ${APP_FRONTEND_URL:http://localhost:5173}
  media:
    supabase:
      url: ${SUPABASE_URL:https://fxxbzrxcakzbbdvxocsu.supabase.co}
      service-key: ${SUPABASE_SERVICE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4eGJ6cnhjYWt6YmJkdnhvY3N1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDg0MDc0MiwiZXhwIjoyMDcwNDE2NzQyfQ.D3T6cY6Qp6Uqb2jlsFyAVsRs1A8UGfyTt63PkvZqmho}
      bucket: ${SUPABASE_STORAGE_BUCKET:menu-images}
